### ISSUE TITLE
[공통] 색상 선택 컴포넌트 구현

### ISSUE THREAD

**Issue by hijiyun** [sprint-part3-team11/taskify#12]
## 📌 기능설명
색상을 선택하면 체크 표시가 됩니다.
버튼을 클릭하면 아주 작은 동그라미에 선택한 색상이 표시됩니다

## 📌 ToDo
- [ ] 색상 카테고리 동그라미로 만들기
- [ ] 색상 클릭시 체크 아이콘 나오게 하기
- [ ] 버튼 클릭 시 선택한 색상 조그만 동그라미에 나오게 하기
