### ISSUE TITLE
[API] 대시보드 수정, 삭제 API 구현

### ISSUE THREAD

**Issue by minjo0n61** [sprint-part3-team11/taskify#127]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!

## 📌 ToDo
- [x] 대시보드 수정, 삭제 react-query useMutation 사용하여 제작
- [x] 수정, 삭제 로직 적용
- [x] UI 수정
- [x] PC 화면 일 때 컬럼 좌우 이동 버튼

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
