### ISSUE TITLE
[공통] 메인 헤더 컴포넌트 구현

### ISSUE THREAD

**Issue by sihyonn** [sprint-part3-team11/taskify#16]
## 📌 기능설명
메인로고와 로그인,회원가입 메뉴가 있는 반응형 메인 헤더를 구현합니다.
<img width="279" alt="image" src="https://github.com/sprint-part3-team11/taskify/assets/124874266/39d1c32e-0b6c-46b0-86d1-792b1df3c422">

## 📌 ToDo
- [ ] `mode` 가 `dark`일때는 검정에 흰색글씨로
- [x] 로그인 | 회원가입은 next의 Link 활용
- [x] 기기에 맞춰 반응형으로 제작

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
