### ISSUE TITLE
[공통] 컬럼 수정(관리) 모달 구현

### ISSUE THREAD

**Issue by minjo0n61** [sprint-part3-team11/taskify#29]
## 📌 기능설명

![image](https://github.com/sprint-part3-team11/taskify/assets/76935187/8257e771-71d2-46d8-be6a-c84c43af0c8e)

기존의 컬럼 이름을 수정하거나 삭제 가능하도록 구현

## 📌 ToDo
- [ ] 공통 컴포넌트 활용
- [ ] prop으로 받은 컬럼 이름 변경 요청 확인 (API 적용 전)
- [ ] 삭제 버튼 구현 (API 적용 전)

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
