### ISSUE TITLE
[공통] 셀렉트 박스 컴포넌트 구현

### ISSUE THREAD

**Issue by hijiyun** [sprint-part3-team11/taskify#3]
## 📌 기능설명

<img width="426" alt="스크린샷 2024-04-14 오후 1 13 59" src="https://github.com/sprint-part3-team11/taskify/assets/114905530/ae156fba-b427-4d91-ad47-f52c6d99c660">

흔히 볼수 있는 셀렉트 박스로, 선택시에 체크 아이콘이 표시됩니다.

## 📌 ToDo
- [x] 셀렉트 박스 생성
- [x] 체크하면 체크 표시 아이콘 삽입
- [x] 오른쪽 화살표로 열고 닫는 기능 생성
