### ISSUE TITLE
[공통] 카드 컴포넌트 구현

### ISSUE THREAD

**Issue by minjo0n61** [sprint-part3-team11/taskify#51]
## 📌 기능설명

<img width="679" alt="스크린샷 2024-04-19 오후 3 27 03" src="https://github.com/sprint-part3-team11/taskify/assets/76935187/b04b40cd-ff4a-4904-b6c4-52b8d19391c5">

## 📌 ToDo
- [x] onProgress, To Do, Done 카테고리에 추가될 카드 컴포넌트 구현
- [x] 이미지, 제목, 태그, 날짜, 인물 아이콘 공통 컴포넌트 가져와서 작업
- [x] 클릭 시 모달 열리게 설정

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
