### ISSUE TITLE
[페이지] 대시보드 수정 페이지 구현

### ISSUE THREAD

**Issue by hyunjun9788** [sprint-part3-team11/taskify#61]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!
![image](https://github.com/sprint-part3-team11/taskify/assets/121845820/fa70c8aa-c406-482c-9878-aa3ed0b5d7ad)

## 📌 ToDo
- [ ] 대시보드 이름이나 색을 바꾸고 '변경' 버튼을 누르면 대시보드가 수정됩니다.
- [ ] '돌아가기' 버튼을 누르면 /boardid로 이동합니다.
- [ ] 대시보드 각 구성원 오른쪽에 있는 '삭제' 버튼을 누르면 구성원이 삭제가 됩니다
- [ ] 구성원 리스트는 페이지네이션으로 구현합니다.
- [ ] 초대 내역 리스트는 페이지네이션으로 구현합니다.
- [ ] '초대하기' 버튼을 누르면 초대하기 모달창이 나타납니다.
- [ ] 초대 내역 각 오른쪽의 '취소'버튼을 누르면 해당 초대는 취소가 됩니다.

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
