### ISSUE TITLE
[공통] 백드롭 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by minjo0n61** [sprint-part3-team11/taskify#7]
## 📌 기능설명
<img width="664" alt="스크린샷 2024-04-15 오전 10 35 02" src="https://github.com/sprint-part3-team11/taskify/assets/76935187/7482c553-e6ae-4934-b7d5-d6d77ed719df">

초기 모달 설정(백드롭 모달)

## 📌 ToDo
- [x] 버튼 클릭 시 모달 생성
- [x] 모달 제외한 뒷배경 어둡게 구현
- [x] 모달 생성 시 뒷배경 스크롤 제한되도록 구현
- [x] 모달 제외한 뒷배경 클릭 시 모달 닫히도록 구현
- [x] 전역적으로 사용 가능하도록 구현
