### ISSUE TITLE
[API] 사이드바 API 연결 

### ISSUE THREAD

**Issue by hijiyun** [sprint-part3-team11/taskify#80]
## 📌 기능설명
- api/dashboards.api.ts 폴더 생성
- 사이드바 API연결 => 대시보드 목록 조회API
- 대시보드 생성 모달 API연결 => 대시보드 생성API

## 📌 ToDo
- [ ] api/dashboards.api.ts 폴더 생성
- [ ] 사이드바 API연결 => 대시보드 목록 조회API
- [ ] 대시보드 생성 모달 API연결 => 대시보드 생성API

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
