### ISSUE TITLE
[API] 상세 모달 API 연결

### ISSUE THREAD

**Issue by hyunjun9788** [sprint-part3-team11/taskify#83]
## 📌 기능설명
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!

## 📌 ToDo
- [ ] 해시태그 API 받아오기
- [ ] 댓글 생성, 수정, 삭제, 목록 조회 API 연결
- [ ] 담당자, 마감일 API
- [ ]  내용, 이미지 API

## 🤔 ETC[선택]
기타사항! (특별히 전달할 내용 or 질문 등등)
